### ISSUE TITLE
Realizar API REST

### ISSUE THREAD

**Issue by adrfergonsos** [gti-sos/SOS1819-04#10]
Realizar una API REST que ofrezca todos los métodos del recurso con la fuente de datos por parte de cada integrante del grupo (cada uno con su fuente de datos)  de forma similar a como se desarrolló en clase.

Aclaraciones:
1.  La API ha de estar desplegada en la ruta /api/v1/YYYYYY de heroku, siendo "YYYYYY" el nombre de la fuente de datos, indicado para cada alumno en su propuesta de trabajo.
2.  El recurso debe contener una ruta /api/v1/YYYYYY/loadInitialData que al hacer un GET cree 2 o más recursos.

**Comment by adrfergonsos** [comment]
Realizada API REST. 
He hecho mi parte de la API REST, quedan las otras dos que se harán sobre el mismo código del index.js que se encuentra en la rama "F03" del repositorio.

**Comment by juanpedroC** [comment]
API realizada y funcionando en el workspace personal. Probado en Postman a falta de realizar el documento. El workspace del grupo no se llega a ejecutar por un fallo con los puertos.
Parte de Heroku no realizada.
