### ISSUE TITLE
Realizar pruebas con POSTMAN sobre la API REST

### ISSUE THREAD

**Issue by adrfergonsos** [gti-sos/SOS1819-04#11]
Realizar un conjunto de pruebas de POSTMANde la API en una colección denominada SOS1819-XX-YYYYYY lista para ser lanzada.

Las pruebas serán las siguientes:
1. GET a la ruta base (p.e. “/towns”) devuelve una lista con todos los recursos.
2. POST a la ruta base (p.e. “/towns”) crea un nuevo recurso.
3. GET a un recurso (p.e. “/towns/seville”) devuelve ese recurso. 
4. DELETE a un recurso (p.e. “/towns/seville”) borra ese recurso.
5. PUT a un recurso (p.e. “/towns/seville”) actualiza ese recurso.
6. POST a un recurso (p.e. “/towns/seville”) debe dar un error de método no permitido.
7. PUT a la ruta base (p.e. “/towns”) debe dar un error de método no permitido.
8. DELETE a la ruta base (p.e. “/towns”) borra todos los recursos.

**Comment by adrfergonsos** [comment]
Todas las pruebas de POSTMAN programadas.

Las pruebas se realizan sobre el servidor web desplegado desde Cloud9 y no desde Heroku, dado que no he conseguido actualizar Heroku añadiéndole la API REST.

**Comment by juanpedroC** [comment]
Pruebas realizadas desde Cloud 9. Guardadas en una colección en modo local.
