### ISSUE TITLE
Revisar Código de la API REST

### ISSUE THREAD

**Issue by adrfergonsos** [gti-sos/SOS1819-04#12]
Revisar el código de la API REST de cada integrante del grupo, teniendo especial cuidado con los puntos mostrados a continuación:

- Han de cumplirse todas las normas de la tabla azul.
- Han de devolverse los códigos de estado de la tabla verde.

**Comment by adrfergonsos** [comment]
Revisado código de index.js.

- Se respetan todas las operaciones de la tabla azul.
- Todos los valores de la tabla verde se devuelven correctamente.

**Comment by juanpedroC** [comment]
Revisados los 3 códigos y funcionando en Cloud 9. No hay ninguna incompatibilida ya. 

- Cada API se ha basado en el mismo esquema y estructura que el de @adrfergonsos
