### ISSUE TITLE
Crear Base de Datos en MongoDB

### ISSUE THREAD

**Issue by adrfergonsos** [gti-sos/SOS1819-04#15]
Crear una Base de Datos en MongoDB Atlas para enlazarla con la API REST correspondiente a cada alumno con motivo de conseguir que sea persistente.

Será indispensable crear la base de datos antes de comenzar con  la API REST.

**Comment by adrfergonsos** [comment]
Creada Cuenta de MongoDB Atlas y enlazada correctamente con mi API REST.

**Comment by juanpedroC** [comment]
Creada Cuenta y enlazada.

**Comment by adrfergonsos** [comment]
Todas las cuentas creadas, CIERRO ISSUE
