### ISSUE TITLE
Crear index.html

### ISSUE THREAD

**Issue by adrfergonsos** [gti-sos/SOS1819-04#2]
Crear un archivo "index.html" tal y como se hizo en prácticas e incluirlo en la carpeta "public" dentro del WorkSpace personal de cada integrante del grupo.

El archivo "index.html" ha de contener la misma información que contiene el "Readme.md" que se encuentra en el repositorio de la asignatura.

**Comment by adrfergonsos** [comment]
Creado "index.html" dentro del directorio "public". Dicho archivo contiene la misma información que el "Readme.md" que se encuentra en el repositorio de la asignatura.

No tiene formato html, luego el navegador lo muestra de una forma bastante feo. Corregir si se puede poner para que se muestre de una forma mas agradable en el navegador.

**Comment by adrfergonsos** [comment]
Actualizado index.html

**Comment by amarinme** [comment]
Creado el archivo index.html en la carpeta public

**Comment by amarinme** [comment]
terminado el archivo index.html, ya tiene lo mismo que el archivo readme.md que hay en el repositorio común

**Comment by juanpedroC** [comment]
Arreglada mi carpeta public en "l05", añadido index.html

**Comment by juanpedroC** [comment]
Creado el contenido en index.html, a falta de un arreglo para no tener problemas con los caracteres

**Comment by juanpedroC** [comment]
Corregido y arreglados los problemas.
