### ISSUE TITLE
Programar las Issues del Segundo FeedBack

### ISSUE THREAD

**Issue by adrfergonsos** [gti-sos/SOS1819-04#3]
Programas las Issues para la segunda sesión de FeedBack de SOS.

**Comment by adrfergonsos** [comment]
He programado 8 Issues para la segunda sesión de FeedBack. En un principio no hay nada más que hacer.

Dejo tarea abierta, cerrar tras conformidad del grupo.

**Comment by amarinme** [comment]
Voy a cerrar esta issues, ya que, al estar todas las issues necesarias para el feedback creadas, esta completada.
