### ISSUE TITLE
Completar la Ficha del Trabajo

### ISSUE THREAD

**Issue by adrfergonsos** [gti-sos/SOS1819-04#6]
Completar la Ficha del Trabajo de la asignatura de SOS.

Toda la información sobre la ficha en el BackLog de SOS (goo.gl/65b1TR)

Observaciones:
    ·) Incluir, al menos, 5 ejemplos reales de datos.
    ·) Comprobar que estén correctos todos los campos (numéricos y no numéricos).

**Comment by adrfergonsos** [comment]
Completados datos de muestra reales de Adrián Fernández González.

Datos Incluidos:
country | years | no_suicides_man | no_suicides_woman | rank

hong kong | 2011 | 10.6 | 13.8 | 39
lituania | 2012 | 54.7 | 10.8 | 3
corea del sur | 2012 | 38.2 | 18 | 6
reino unido | 2011 | 18.2 | 5.1 | 45
groenlandia | 2011 | 116.9 | 45 | 1

**Comment by amarinme** [comment]
Completado con los datos reales la plantilla

**Comment by juanpedroC** [comment]
Completados datos de muestra reales de Juan Pedro Carmona Castaño

Datos Incluidos:
countries | years | rating | variation | country_consumition

-- | -- | -- | -- | --
spain | 2016 | 84.8 | 2 | 3909
germany | 2016 | 104.2 | -0.5 | 8412
reino unido | 2016 | 67.7 | 1.6 | 4373
lithuania | 2016 | 88.7 | -8.4 | 257
south korea | 2016 | 42.8 | 0.3 | 2160
