### ISSUE TITLE
Crear Documento SOS1819-04-YYY en Drive

### ISSUE THREAD

**Issue by adrfergonsos** [gti-sos/SOS1819-04#7]
Crear un documento en Google Docs llamado SOS1819-04-YYY (siendo YYY las siglas del nombre del alumno en mayúsculas) y compartido con el profesor (pafmon@gmail.com) explicando la API correspondiente a la fuente de datos siguiendo el formato del ejemplo del BackLog (goo.gl/65b1TR) y extendido para mostrar TODAS las operaciones de la “tabla azul” de forma que tengan un ejemplo de datos de petición y/o respuesta y el código de estado devuelto (cuando sea distinto de 200).

Mas info en BlackLog de la asignatura de SOS (goo.gl/65b1TR)

**Comment by adrfergonsos** [comment]
Creado Archivo "SOS1819-04-AFG" en la carpeta "Archivos Individuales"y compartido con el profesor.

Podeis usarlo de plantilla para las órdenes que no viene en la plantilla del profesor.

**Comment by amarinme** [comment]
Creado el archivo SOS1819-04-AMM y compartido con el profesor

**Comment by amarinme** [comment]
Ya he completado el documento de Drive siguiendo el ejemplo de la plantilla que el profesor ha dado

**Comment by juanpedroC** [comment]
Creado el archivo y compartido. Pendiente de completarlo.

**Comment by juanpedroC** [comment]
Documento finalizado.
