### ISSUE TITLE
Desplegar el Proyecto de Grupo en Heroku

### ISSUE THREAD

**Issue by adrfergonsos** [gti-sos/SOS1819-04#8]
Desplegar el proyecto del grupo en Heroku siguiendo las instrucciones del vídeo que se encuentra en el enlace mostrado abajo , de forma que esté accesible en https://sos1819-04.herokuapp.com/.

Enlace de Vídeo:
    ·) https://drive.google.com/file/d/1_IfWEYDTCMMq4j6bGW1wyQkFKdMrIuz9/view

**Comment by adrfergonsos** [comment]
Creada App en Heroku.

No me hace el "git push heroku", que alguien pruebe a repetir el proceso a ver si es capaz de arreglarlo.

**Comment by amarinme** [comment]
he repetido el proceso y no he conseguido hacerlo

**Comment by juanpedroC** [comment]
Siguiendo el vídeo, en el paso de:
$ git push heroku

obtenemos como respuesta:                                                                            
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.
